### ISSUE TITLE
MongoDB可以使用了

### ISSUE THREAD

**Issue by r1235613** [r1235613/apc_simulator#2]
目前測試MongoDB可以正常使用，URL暫訂 `mongodb`，可以在[index 46](https://github.com/r1235613/apc_simulator/blob/b76625cde9a4a65356ccacc310bdd71c49b0393a/src/index.js#L46)行設定。

**Comment by takidog** [comment]
可以改成環境變數嗎

對Container的部署會更友善些

或是有共同設定檔

**Comment by r1235613** [comment]
@takidog 看起來你改好了，我關issue囉
